name: vision_mobile
description: "Vision AI Assistant Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Core Logic
  http: ^1.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  
  # Media
  camera: ^0.10.5
  record: ^5.1.0
  audioplayers: ^6.0.0
  image_picker: ^1.0.7
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  animate_do: ^3.3.4
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # Enable l10n generation
