name: way_finder
description: "WayFinder AI Assistant"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Core Logic
  http: ^1.2.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  
  # Media
  camera: ^0.10.5
  record: ^6.0.0
  audioplayers: ^6.0.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  path_provider: ^2.1.2
  speech_to_text: ^7.0.0
  porcupine_flutter: ^3.0.1
  google_sign_in: ^6.1.6
  
  # Navigation
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  
  # UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.10
  animate_do: ^3.3.4
  loading_animation_widget: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true # Enable l10n generation
  assets:
    - assets/words/way_finder_android.ppn
